### ISSUE TITLE
[question] What about security the api-key?

### ISSUE THREAD

**Issue by emanuel-braz** [SwaroopSambhayya/Iris#5]
Hello, I'm creating a project that uses the same GPT lib, If you can share your thoughts, a question I have is: What do you think about keeping the api-key in the app, or using a service like Remote config to store the api-key? I've been wondering if it wouldn't be better to have a backend layer to mediate this access.

**Comment by shahbazakon** [comment]
Remember, while these measures improve security, they may not make it completely foolproof. Always be vigilant and stay informed about best practices for API key security.
